/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/layout/components/AppMain/index.vue')['default']
    Box: typeof import('./src/components/Box/index.vue')['default']
    BoxItem: typeof import('./src/layout/components/AppMain/BoxItem.vue')['default']
    Conent: typeof import('./src/layout/components/AppMain/conent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTree: typeof import('element-plus/es')['ElTree']
    Left: typeof import('./src/layout/components/AppMain/Left.vue')['default']
    Link: typeof import('./src/layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./src/layout/components/Sidebar/Logo.vue')['default']
    MainLeft: typeof import('./src/layout/components/AppMain/MainLeft.vue')['default']
    MainRight: typeof import('./src/layout/components/AppMain/MainRight.vue')['default']
    Right: typeof import('./src/layout/components/AppMain/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/layout/components/Sidebar/SidebarItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    Website: typeof import('./src/components/Website/index.vue')['default']
  }
}
